# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_industry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='案件産業'),
        ),
    ]
